model_name: dgcnn

data:
  task: segmentation
  class: SegmentationDataset
  number_of_classes: 3
  dataroot: pointclouds
  use_cache: false
  load_features: false
  prepare_data: false
  train_transforms: []
  test_transforms: []
  class_weights: [1.0, 4.0, 4.0]

model:
  name: DGCNN
  conv_type: "DENSE"
  use_category: false
  use_norm: True
  first_feats_dim: 64
  k: 20  # number of neighbors for graph construction
  aggr: max  # aggregation method: max, mean, add
  dropout: 0.5
  mlp_cls: [64, 128, 256]
  mlp_embed: [64, 64]
  use_dropout: True

training:
  batch_size: 1
  lr: 0.001
  weight_decay: 0
  epochs: 20
  shuffle: True
  loss: cross_entropy
